### ISSUE TITLE
Include expected response data in specification

### ISSUE THREAD

**Issue by joustava** [ttezel/unio#17]
Might it be benificial to include a json description of the expected data in the response?
This could make it possible to have a client user to supply callbacks to instantiate objects or parse response data.

**Comment by ttezel** [comment]
One of the primary goals of unio is to make it as quick and painless as possible to start using a new REST API. For that reason, I believe the design should be geared towards API consumption, rather than API validation (validating the response). Therefore I don't want to include response data specification in the specs.
