### ISSUE TITLE
Easier specs?

### ISSUE THREAD

**Issue by ryan-endacott** [ttezel/unio#5]
I was looking at how [APIhub](http://www.apihub.com/api/github-api) stores the JSON description of an API, and I was wondering if it would be worth it to use specs in that style?  APIhub seems to have a decent many of them already [mapped](http://www.apihub.com/apihub/swagger-api/9528/commits) out. (Note:  View it more easily [here](http://www.jsoneditoronline.org/))  At the very least, more specs could be crawled from that data.  (If that's legal and morally okay).

**Comment by ttezel** [comment]
I feel like the APIhub representation is too bloated. I'd imagine it would be a much greater pain to maintain one of those specs than a typical unio spec (check out the specs folder for examples). Since the primary purpose with unio is to make it as quick and painless as possible to talk to a REST API, I prefer to stick with the current format. If needed, it is certainly possible to transform an APIhub spec to a unio spec with a simple script.
